// The CSS surface is public API. docs/release-process.md says so explicitly: "a renamed --cui-*
// variable or .cui-* class is exactly as breaking as a renamed prop." Until this script existed
// nothing enforced that. pnpm api:check covers the TypeScript entry points, and the generated
// token module carries --cui-* variable names into etc/product-ui-tokens.api.md, but class names
// and data-cui-* attributes appeared nowhere: renaming .cui-input would have passed every check in
// CI and silently broken any consumer styling against it, including the CSS-only consumers the
// theming docs explicitly support.
//
// This mirrors api:check deliberately, so there is one habit to learn rather than two: it diffs
// the compiled surface against a committed snapshot and fails on any difference, and `pnpm
// css:update` accepts an intentional change so the diff shows a reviewer exactly what moved.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('../', import.meta.url)
const cssPath = new URL('dist/styles.css', root)
const snapshotPath = new URL('etc/product-ui.css.md', root)
const update = process.argv.includes('--update')

let css
try {
  css = readFileSync(cssPath, 'utf8')
} catch {
  console.error('dist/styles.css not found. Run pnpm build first (pnpm css:check does this for you).')
  process.exit(1)
}

const unique = (matches) => [...new Set(matches)].sort()
// Class selectors, e.g. `.cui-button-primary`. Excludes anything not in the cui- namespace, since
// Tailwind authoring utilities (cdu- prefix) are not part of the published surface.
const classes = unique([...css.matchAll(/\.(cui-[a-zA-Z0-9_-]+)/g)].map((m) => m[1]))
// Custom properties as *defined* by this stylesheet, not merely referenced via var().
const variables = unique([...css.matchAll(/(--cui-[a-zA-Z0-9_-]+)\s*:/g)].map((m) => m[1]))
// data-cui-* attributes a consumer can set or select on, e.g. data-cui-theme.
const attributes = unique([...css.matchAll(/\[(data-cui-[a-zA-Z0-9_-]+)/g)].map((m) => m[1]))

const section = (title, items) => `## ${title} (${items.length})\n\n${items.map((i) => `- \`${i}\``).join('\n')}\n`

const snapshot = `<!-- Generated by scripts/check-css.mjs. Do not edit by hand. Run pnpm css:update to accept an intentional change. -->

# Public CSS surface

Every class, custom property and data attribute the compiled \`dist/styles.css\` exposes to consumers. Renaming or removing anything here is a breaking change under [docs/release-process.md](../docs/release-process.md#backward-compatibility), exactly like renaming a prop. Additions are compatible.

${section('Classes', classes)}
${section('Custom properties', variables)}
${section('Data attributes', attributes)}`

if (update) {
  writeFileSync(snapshotPath, snapshot)
  console.log(
    `CSS surface snapshot updated: ${classes.length} classes, ${variables.length} custom properties, ${attributes.length} data attributes.`,
  )
  process.exit(0)
}

let existing
try {
  existing = readFileSync(snapshotPath, 'utf8')
} catch {
  console.error(`No CSS surface snapshot at ${fileURLToPath(snapshotPath)}. Run pnpm css:update and commit the result.`)
  process.exit(1)
}

if (existing === snapshot) {
  console.log(
    `CSS surface unchanged: ${classes.length} classes, ${variables.length} custom properties, ${attributes.length} data attributes.`,
  )
  process.exit(0)
}

const lines = (text) => new Set(text.split('\n').filter((l) => l.startsWith('- `')))
const before = lines(existing)
const after = lines(snapshot)
const removed = [...before].filter((l) => !after.has(l))
const added = [...after].filter((l) => !before.has(l))

console.error('The public CSS surface changed.\n')
if (removed.length) {
  console.error(`Removed or renamed (BREAKING for consumers, see docs/release-process.md):`)
  for (const l of removed) console.error(`  -${l.slice(1)}`)
  console.error('')
}
if (added.length) {
  console.error('Added (compatible):')
  for (const l of added) console.error(`  +${l.slice(1)}`)
  console.error('')
}
console.error('If this is intentional, run pnpm css:update and commit etc/product-ui.css.md with the change.')
process.exit(1)
