// Generated from tokens/tokens.json by generate-tokens.mjs.
export const tokenReference = [
  {
    "group": "colour",
    "name": "ink",
    "key": "colour.ink",
    "css": "--cui-colour-ink",
    "value": "#171717",
    "description": "Product text base",
    "resolved": "#171717",
    "darkResolved": "#171717"
  },
  {
    "group": "colour",
    "name": "muted",
    "key": "colour.muted",
    "css": "--cui-colour-muted",
    "value": "#5e665f",
    "description": "Secondary text base",
    "resolved": "#5e665f",
    "darkResolved": "#5e665f"
  },
  {
    "group": "colour",
    "name": "paper",
    "key": "colour.paper",
    "css": "--cui-colour-paper",
    "value": "#faf9f7",
    "description": "Warm page base",
    "resolved": "#faf9f7",
    "darkResolved": "#faf9f7"
  },
  {
    "group": "colour",
    "name": "band",
    "key": "colour.band",
    "css": "--cui-colour-band",
    "value": "#eef0ec",
    "description": "Neutral section base",
    "resolved": "#eef0ec",
    "darkResolved": "#eef0ec"
  },
  {
    "group": "colour",
    "name": "white",
    "key": "colour.white",
    "css": "--cui-colour-white",
    "value": "#ffffff",
    "description": "Card base",
    "resolved": "#ffffff",
    "darkResolved": "#ffffff"
  },
  {
    "group": "colour",
    "name": "line",
    "key": "colour.line",
    "css": "--cui-colour-line",
    "value": "#dce2db",
    "description": "Subtle separation",
    "resolved": "#dce2db",
    "darkResolved": "#dce2db"
  },
  {
    "group": "colour",
    "name": "control",
    "key": "colour.control",
    "css": "--cui-colour-control",
    "value": "#829080",
    "description": "Control outline",
    "resolved": "#829080",
    "darkResolved": "#829080"
  },
  {
    "group": "colour",
    "name": "forest",
    "key": "colour.forest",
    "css": "--cui-colour-forest",
    "value": "#27382f",
    "description": "Convert brand-900",
    "resolved": "#27382f",
    "darkResolved": "#27382f"
  },
  {
    "group": "colour",
    "name": "sage",
    "key": "colour.sage",
    "css": "--cui-colour-sage",
    "value": "#c9deb6",
    "description": "Convert brand-300",
    "resolved": "#c9deb6",
    "darkResolved": "#c9deb6"
  },
  {
    "group": "colour",
    "name": "chart",
    "key": "colour.chart",
    "css": "--cui-colour-chart",
    "value": "#499e6b",
    "description": "Convert brand-500; graphical accent, not small text",
    "resolved": "#499e6b",
    "darkResolved": "#499e6b"
  },
  {
    "group": "colour",
    "name": "positive",
    "key": "colour.positive",
    "css": "--cui-colour-positive",
    "value": "#2f6b45",
    "description": "Positive text",
    "resolved": "#2f6b45",
    "darkResolved": "#2f6b45"
  },
  {
    "group": "colour",
    "name": "warning",
    "key": "colour.warning",
    "css": "--cui-colour-warning",
    "value": "#8a5a1a",
    "description": "Caution text; the amber of a three-state red/amber/green status",
    "resolved": "#8a5a1a",
    "darkResolved": "#8a5a1a"
  },
  {
    "group": "colour",
    "name": "negative",
    "key": "colour.negative",
    "css": "--cui-colour-negative",
    "value": "#a13d32",
    "description": "Negative and error text",
    "resolved": "#a13d32",
    "darkResolved": "#a13d32"
  },
  {
    "group": "surface",
    "name": "page",
    "key": "surface.page",
    "css": "--cui-surface-page",
    "value": "{colour.paper}",
    "description": "Page canvas",
    "dark": "#171c19",
    "resolved": "#faf9f7",
    "darkResolved": "#171c19"
  },
  {
    "group": "surface",
    "name": "band",
    "key": "surface.band",
    "css": "--cui-surface-band",
    "value": "{colour.band}",
    "description": "Group related cards",
    "dark": "#202823",
    "resolved": "#eef0ec",
    "darkResolved": "#202823"
  },
  {
    "group": "surface",
    "name": "card",
    "key": "surface.card",
    "css": "--cui-surface-card",
    "value": "{colour.white}",
    "description": "Content surface",
    "dark": "#28312b",
    "resolved": "#ffffff",
    "darkResolved": "#28312b"
  },
  {
    "group": "surface",
    "name": "selected",
    "key": "surface.selected",
    "css": "--cui-surface-selected",
    "value": "{colour.sage}",
    "description": "Current navigation (aria-current) and calendar range selection. Not for dropdown/listbox options — see dropdown.selected.",
    "dark": "{colour.forest}",
    "resolved": "#c9deb6",
    "darkResolved": "#27382f"
  },
  {
    "group": "surface",
    "name": "warning",
    "key": "surface.warning",
    "css": "--cui-surface-warning",
    "value": "#f7e6c8",
    "description": "Soft caution background behind text.warning",
    "dark": "#3a2e18",
    "resolved": "#f7e6c8",
    "darkResolved": "#3a2e18"
  },
  {
    "group": "surface",
    "name": "hover",
    "key": "surface.hover",
    "css": "--cui-surface-hover",
    "value": "{colour.band}",
    "description": "Neutral hover feedback",
    "dark": "#344139",
    "resolved": "#eef0ec",
    "darkResolved": "#344139"
  },
  {
    "group": "dropdown",
    "name": "hover",
    "key": "dropdown.hover",
    "css": "--cui-dropdown-hover",
    "value": "{colour.band}",
    "description": "Dropdown/listbox option hover — scoped separately from surface.hover so tuning it never touches buttons, tabs or menus",
    "dark": "#344139",
    "resolved": "#eef0ec",
    "darkResolved": "#344139"
  },
  {
    "group": "dropdown",
    "name": "selected",
    "key": "dropdown.selected",
    "css": "--cui-dropdown-selected",
    "value": "{colour.line}",
    "description": "Dropdown/listbox option's own selected-row background. Deliberately neutral, not surface.selected's brand green — the option's checkmark carries the 'this is selected' meaning, not the row colour, so it never collides with navigation's current-page tint",
    "dark": "#47574b",
    "resolved": "#dce2db",
    "darkResolved": "#47574b"
  },
  {
    "group": "text",
    "name": "primary",
    "key": "text.primary",
    "css": "--cui-text-primary",
    "value": "{colour.ink}",
    "description": "Headings and body",
    "dark": "{colour.paper}",
    "resolved": "#171717",
    "darkResolved": "#faf9f7"
  },
  {
    "group": "text",
    "name": "secondary",
    "key": "text.secondary",
    "css": "--cui-text-secondary",
    "value": "{colour.muted}",
    "description": "Supporting copy",
    "dark": "#bdc7bf",
    "resolved": "#5e665f",
    "darkResolved": "#bdc7bf"
  },
  {
    "group": "text",
    "name": "inverse",
    "key": "text.inverse",
    "css": "--cui-text-inverse",
    "value": "{colour.white}",
    "description": "Text on forest",
    "dark": "{colour.ink}",
    "resolved": "#ffffff",
    "darkResolved": "#171717"
  },
  {
    "group": "text",
    "name": "accent",
    "key": "text.accent",
    "css": "--cui-text-accent",
    "value": "{colour.forest}",
    "description": "Links and interactive emphasis",
    "dark": "{colour.sage}",
    "resolved": "#27382f",
    "darkResolved": "#c9deb6"
  },
  {
    "group": "text",
    "name": "positive",
    "key": "text.positive",
    "css": "--cui-text-positive",
    "value": "{colour.positive}",
    "description": "Positive status with a text label",
    "dark": "#a3d8b4",
    "resolved": "#2f6b45",
    "darkResolved": "#a3d8b4"
  },
  {
    "group": "text",
    "name": "warning",
    "key": "text.warning",
    "css": "--cui-text-warning",
    "value": "{colour.warning}",
    "description": "Caution status with a text label",
    "dark": "#f0c98a",
    "resolved": "#8a5a1a",
    "darkResolved": "#f0c98a"
  },
  {
    "group": "text",
    "name": "negative",
    "key": "text.negative",
    "css": "--cui-text-negative",
    "value": "{colour.negative}",
    "description": "Error and negative status with a text label",
    "dark": "#ffb4a8",
    "resolved": "#a13d32",
    "darkResolved": "#ffb4a8"
  },
  {
    "group": "border",
    "name": "subtle",
    "key": "border.subtle",
    "css": "--cui-border-subtle",
    "value": "{colour.line}",
    "description": "Container separation only",
    "dark": "#47574b",
    "resolved": "#dce2db",
    "darkResolved": "#47574b"
  },
  {
    "group": "border",
    "name": "control",
    "key": "border.control",
    "css": "--cui-border-control",
    "value": "{colour.control}",
    "description": "Visible input boundary",
    "dark": "#95a78f",
    "resolved": "#829080",
    "darkResolved": "#95a78f"
  },
  {
    "group": "border",
    "name": "error",
    "key": "border.error",
    "css": "--cui-border-error",
    "value": "{colour.negative}",
    "description": "Invalid control",
    "dark": "#ffb4a8",
    "resolved": "#a13d32",
    "darkResolved": "#ffb4a8"
  },
  {
    "group": "border",
    "name": "width",
    "key": "border.width",
    "css": "--cui-border-width",
    "value": "1px",
    "description": "Standard border width",
    "resolved": "1px",
    "darkResolved": "1px"
  },
  {
    "group": "accent",
    "name": "primary",
    "key": "accent.primary",
    "css": "--cui-accent-primary",
    "value": "{colour.forest}",
    "description": "Primary action",
    "dark": "{colour.sage}",
    "resolved": "#27382f",
    "darkResolved": "#c9deb6"
  },
  {
    "group": "accent",
    "name": "soft",
    "key": "accent.soft",
    "css": "--cui-accent-soft",
    "value": "{colour.sage}",
    "description": "Selection",
    "dark": "{colour.forest}",
    "resolved": "#c9deb6",
    "darkResolved": "#27382f"
  },
  {
    "group": "accent",
    "name": "chart",
    "key": "accent.chart",
    "css": "--cui-accent-chart",
    "value": "{colour.chart}",
    "description": "Charts and graphical marks",
    "resolved": "#499e6b",
    "darkResolved": "#499e6b"
  },
  {
    "group": "space",
    "name": "0",
    "key": "space.0",
    "css": "--cui-space-0",
    "value": "0px",
    "description": "Approved spacing step",
    "resolved": "0px",
    "darkResolved": "0px"
  },
  {
    "group": "space",
    "name": "4",
    "key": "space.4",
    "css": "--cui-space-4",
    "value": "4px",
    "description": "Approved spacing step",
    "resolved": "4px",
    "darkResolved": "4px"
  },
  {
    "group": "space",
    "name": "8",
    "key": "space.8",
    "css": "--cui-space-8",
    "value": "8px",
    "description": "Approved spacing step",
    "resolved": "8px",
    "darkResolved": "8px"
  },
  {
    "group": "space",
    "name": "12",
    "key": "space.12",
    "css": "--cui-space-12",
    "value": "12px",
    "description": "Approved spacing step",
    "resolved": "12px",
    "darkResolved": "12px"
  },
  {
    "group": "space",
    "name": "16",
    "key": "space.16",
    "css": "--cui-space-16",
    "value": "16px",
    "description": "Approved spacing step",
    "resolved": "16px",
    "darkResolved": "16px"
  },
  {
    "group": "space",
    "name": "20",
    "key": "space.20",
    "css": "--cui-space-20",
    "value": "20px",
    "description": "Approved spacing step",
    "resolved": "20px",
    "darkResolved": "20px"
  },
  {
    "group": "space",
    "name": "24",
    "key": "space.24",
    "css": "--cui-space-24",
    "value": "24px",
    "description": "Approved spacing step",
    "resolved": "24px",
    "darkResolved": "24px"
  },
  {
    "group": "space",
    "name": "32",
    "key": "space.32",
    "css": "--cui-space-32",
    "value": "32px",
    "description": "Approved spacing step",
    "resolved": "32px",
    "darkResolved": "32px"
  },
  {
    "group": "space",
    "name": "40",
    "key": "space.40",
    "css": "--cui-space-40",
    "value": "40px",
    "description": "Approved spacing step",
    "resolved": "40px",
    "darkResolved": "40px"
  },
  {
    "group": "space",
    "name": "48",
    "key": "space.48",
    "css": "--cui-space-48",
    "value": "48px",
    "description": "Approved spacing step",
    "resolved": "48px",
    "darkResolved": "48px"
  },
  {
    "group": "space",
    "name": "64",
    "key": "space.64",
    "css": "--cui-space-64",
    "value": "64px",
    "description": "Approved spacing step",
    "resolved": "64px",
    "darkResolved": "64px"
  },
  {
    "group": "font",
    "name": "sans",
    "key": "font.sans",
    "css": "--cui-font-sans",
    "value": "Roobert, Geist, Arial, sans-serif",
    "description": "Host supplies licensed Roobert; Geist is the fallback",
    "resolved": "Roobert, Geist, Arial, sans-serif",
    "darkResolved": "Roobert, Geist, Arial, sans-serif"
  },
  {
    "group": "font",
    "name": "regular",
    "key": "font.regular",
    "css": "--cui-font-regular",
    "value": "400",
    "description": "Body",
    "resolved": "400",
    "darkResolved": "400"
  },
  {
    "group": "font",
    "name": "medium",
    "key": "font.medium",
    "css": "--cui-font-medium",
    "value": "500",
    "description": "Labels",
    "resolved": "500",
    "darkResolved": "500"
  },
  {
    "group": "font",
    "name": "semibold",
    "key": "font.semibold",
    "css": "--cui-font-semibold",
    "value": "600",
    "description": "Headings and key data",
    "resolved": "600",
    "darkResolved": "600"
  },
  {
    "group": "type",
    "name": "display",
    "key": "type.display",
    "css": "--cui-type-display",
    "value": "2.5rem",
    "description": "40px at default root size",
    "resolved": "2.5rem",
    "darkResolved": "2.5rem"
  },
  {
    "group": "type",
    "name": "display-leading",
    "key": "type.display-leading",
    "css": "--cui-type-display-leading",
    "value": "3rem",
    "description": "48px",
    "resolved": "3rem",
    "darkResolved": "3rem"
  },
  {
    "group": "type",
    "name": "display-mobile",
    "key": "type.display-mobile",
    "css": "--cui-type-display-mobile",
    "value": "2rem",
    "description": "32px",
    "resolved": "2rem",
    "darkResolved": "2rem"
  },
  {
    "group": "type",
    "name": "display-mobile-leading",
    "key": "type.display-mobile-leading",
    "css": "--cui-type-display-mobile-leading",
    "value": "2.5rem",
    "description": "40px",
    "resolved": "2.5rem",
    "darkResolved": "2.5rem"
  },
  {
    "group": "type",
    "name": "section",
    "key": "type.section",
    "css": "--cui-type-section",
    "value": "1.25rem",
    "description": "20px",
    "resolved": "1.25rem",
    "darkResolved": "1.25rem"
  },
  {
    "group": "type",
    "name": "section-leading",
    "key": "type.section-leading",
    "css": "--cui-type-section-leading",
    "value": "1.75rem",
    "description": "28px",
    "resolved": "1.75rem",
    "darkResolved": "1.75rem"
  },
  {
    "group": "type",
    "name": "body",
    "key": "type.body",
    "css": "--cui-type-body",
    "value": "1rem",
    "description": "16px",
    "resolved": "1rem",
    "darkResolved": "1rem"
  },
  {
    "group": "type",
    "name": "body-leading",
    "key": "type.body-leading",
    "css": "--cui-type-body-leading",
    "value": "1.5rem",
    "description": "24px",
    "resolved": "1.5rem",
    "darkResolved": "1.5rem"
  },
  {
    "group": "type",
    "name": "compact",
    "key": "type.compact",
    "css": "--cui-type-compact",
    "value": ".875rem",
    "description": "14px",
    "resolved": ".875rem",
    "darkResolved": ".875rem"
  },
  {
    "group": "type",
    "name": "compact-leading",
    "key": "type.compact-leading",
    "css": "--cui-type-compact-leading",
    "value": "1.25rem",
    "description": "20px",
    "resolved": "1.25rem",
    "darkResolved": "1.25rem"
  },
  {
    "group": "type",
    "name": "caption",
    "key": "type.caption",
    "css": "--cui-type-caption",
    "value": ".75rem",
    "description": "12px",
    "resolved": ".75rem",
    "darkResolved": ".75rem"
  },
  {
    "group": "type",
    "name": "caption-leading",
    "key": "type.caption-leading",
    "css": "--cui-type-caption-leading",
    "value": "1rem",
    "description": "16px",
    "resolved": "1rem",
    "darkResolved": "1rem"
  },
  {
    "group": "type",
    "name": "data",
    "key": "type.data",
    "css": "--cui-type-data",
    "value": "1.5rem",
    "description": "24px",
    "resolved": "1.5rem",
    "darkResolved": "1.5rem"
  },
  {
    "group": "type",
    "name": "data-leading",
    "key": "type.data-leading",
    "css": "--cui-type-data-leading",
    "value": "2rem",
    "description": "32px",
    "resolved": "2rem",
    "darkResolved": "2rem"
  },
  {
    "group": "type",
    "name": "tracking-display",
    "key": "type.tracking-display",
    "css": "--cui-type-tracking-display",
    "value": "-.02em",
    "description": "Display tracking",
    "resolved": "-.02em",
    "darkResolved": "-.02em"
  },
  {
    "group": "type",
    "name": "tracking-heading",
    "key": "type.tracking-heading",
    "css": "--cui-type-tracking-heading",
    "value": "-.01em",
    "description": "Section tracking",
    "resolved": "-.01em",
    "darkResolved": "-.01em"
  },
  {
    "group": "radius",
    "name": "band",
    "key": "radius.band",
    "css": "--cui-radius-band",
    "value": "16px",
    "description": "Section containment",
    "resolved": "16px",
    "darkResolved": "16px"
  },
  {
    "group": "radius",
    "name": "card",
    "key": "radius.card",
    "css": "--cui-radius-card",
    "value": "12px",
    "description": "Content cards",
    "resolved": "12px",
    "darkResolved": "12px"
  },
  {
    "group": "radius",
    "name": "control",
    "key": "radius.control",
    "css": "--cui-radius-control",
    "value": "8px",
    "description": "Inputs and buttons",
    "resolved": "8px",
    "darkResolved": "8px"
  },
  {
    "group": "radius",
    "name": "round",
    "key": "radius.round",
    "css": "--cui-radius-round",
    "value": "50%",
    "description": "Circular marks",
    "resolved": "50%",
    "darkResolved": "50%"
  },
  {
    "group": "shadow",
    "name": "card",
    "key": "shadow.card",
    "css": "--cui-shadow-card",
    "value": "0 4px 12px rgba(23, 23, 23, 0.06)",
    "description": "Koko V4 card elevation; avoid nested elevated cards",
    "dark": "0 4px 12px rgba(0, 0, 0, 0.2)",
    "resolved": "0 4px 12px rgba(23, 23, 23, 0.06)",
    "darkResolved": "0 4px 12px rgba(0, 0, 0, 0.2)"
  },
  {
    "group": "shadow",
    "name": "none",
    "key": "shadow.none",
    "css": "--cui-shadow-none",
    "value": "none",
    "description": "Flat containment",
    "resolved": "none",
    "darkResolved": "none"
  },
  {
    "group": "focus",
    "name": "colour",
    "key": "focus.colour",
    "css": "--cui-focus-colour",
    "value": "{colour.forest}",
    "description": "Visible keyboard outline",
    "dark": "{colour.sage}",
    "resolved": "#27382f",
    "darkResolved": "#c9deb6"
  },
  {
    "group": "focus",
    "name": "width",
    "key": "focus.width",
    "css": "--cui-focus-width",
    "value": "2px",
    "description": "Outline width",
    "resolved": "2px",
    "darkResolved": "2px"
  },
  {
    "group": "focus",
    "name": "offset",
    "key": "focus.offset",
    "css": "--cui-focus-offset",
    "value": "0px",
    "description": "Outline offset. Flush against the element's own border, not floating with a gap.",
    "resolved": "0px",
    "darkResolved": "0px"
  },
  {
    "group": "size",
    "name": "control",
    "key": "size.control",
    "css": "--cui-size-control",
    "value": "40px",
    "description": "Desktop minimum",
    "resolved": "40px",
    "darkResolved": "40px"
  },
  {
    "group": "size",
    "name": "touch",
    "key": "size.touch",
    "css": "--cui-size-touch",
    "value": "48px",
    "description": "Touch minimum",
    "resolved": "48px",
    "darkResolved": "48px"
  },
  {
    "group": "size",
    "name": "row",
    "key": "size.row",
    "css": "--cui-size-row",
    "value": "44px",
    "description": "Reference row minimum; allow content growth",
    "resolved": "44px",
    "darkResolved": "44px"
  },
  {
    "group": "size",
    "name": "icon",
    "key": "size.icon",
    "css": "--cui-size-icon",
    "value": "20px",
    "description": "Standard icon",
    "resolved": "20px",
    "darkResolved": "20px"
  },
  {
    "group": "size",
    "name": "icon-small",
    "key": "size.icon-small",
    "css": "--cui-size-icon-small",
    "value": "16px",
    "description": "Compact icon",
    "resolved": "16px",
    "darkResolved": "16px"
  },
  {
    "group": "size",
    "name": "brand",
    "key": "size.brand",
    "css": "--cui-size-brand",
    "value": "24px",
    "description": "Convert stack mark",
    "resolved": "24px",
    "darkResolved": "24px"
  },
  {
    "group": "size",
    "name": "sidebar",
    "key": "size.sidebar",
    "css": "--cui-size-sidebar",
    "value": "208px",
    "description": "Koko desktop sidebar width",
    "resolved": "208px",
    "darkResolved": "208px"
  },
  {
    "group": "size",
    "name": "rail",
    "key": "size.rail",
    "css": "--cui-size-rail",
    "value": "64px",
    "description": "Collapsed navigation rail width, icons only",
    "resolved": "64px",
    "darkResolved": "64px"
  },
  {
    "group": "size",
    "name": "content",
    "key": "size.content",
    "css": "--cui-size-content",
    "value": "1280px",
    "description": "Maximum page content width",
    "resolved": "1280px",
    "darkResolved": "1280px"
  },
  {
    "group": "motion",
    "name": "duration",
    "key": "motion.duration",
    "css": "--cui-motion-duration",
    "value": "160ms",
    "description": "Short interface feedback",
    "resolved": "160ms",
    "darkResolved": "160ms"
  },
  {
    "group": "motion",
    "name": "easing",
    "key": "motion.easing",
    "css": "--cui-motion-easing",
    "value": "ease-out",
    "description": "Restrained transitions",
    "resolved": "ease-out",
    "darkResolved": "ease-out"
  },
  {
    "group": "breakpoint",
    "name": "mobile",
    "key": "breakpoint.mobile",
    "css": "--cui-breakpoint-mobile",
    "value": "650px",
    "description": "Compact content and touch controls",
    "resolved": "650px",
    "darkResolved": "650px"
  },
  {
    "group": "breakpoint",
    "name": "sidebar",
    "key": "breakpoint.sidebar",
    "css": "--cui-breakpoint-sidebar",
    "value": "900px",
    "description": "Mobile navigation starts below desktop sidebar width",
    "resolved": "900px",
    "darkResolved": "900px"
  },
  {
    "group": "layer",
    "name": "navigation",
    "key": "layer.navigation",
    "css": "--cui-layer-navigation",
    "value": "20",
    "description": "Desktop sidebar and mobile header",
    "resolved": "20",
    "darkResolved": "20"
  },
  {
    "group": "layer",
    "name": "overlay",
    "key": "layer.overlay",
    "css": "--cui-layer-overlay",
    "value": "40",
    "description": "Modal backdrop",
    "resolved": "40",
    "darkResolved": "40"
  },
  {
    "group": "layer",
    "name": "dialog",
    "key": "layer.dialog",
    "css": "--cui-layer-dialog",
    "value": "50",
    "description": "Mobile navigation panel",
    "resolved": "50",
    "darkResolved": "50"
  },
  {
    "group": "chart",
    "name": "series-primary",
    "key": "chart.series-primary",
    "css": "--cui-chart-series-primary",
    "value": "{colour.forest}",
    "description": "Primary chart series and progress fill",
    "dark": "{colour.sage}",
    "resolved": "#27382f",
    "darkResolved": "#c9deb6"
  },
  {
    "group": "chart",
    "name": "series-secondary",
    "key": "chart.series-secondary",
    "css": "--cui-chart-series-secondary",
    "value": "{colour.chart}",
    "description": "Secondary chart series; pair with labels and line styles",
    "dark": "#72be90",
    "resolved": "#499e6b",
    "darkResolved": "#72be90"
  },
  {
    "group": "chart",
    "name": "series-tertiary",
    "key": "chart.series-tertiary",
    "css": "--cui-chart-series-tertiary",
    "value": "{colour.muted}",
    "description": "Third chart series; pair with labels and line styles",
    "dark": "#bdc7bf",
    "resolved": "#5e665f",
    "darkResolved": "#bdc7bf"
  },
  {
    "group": "chart",
    "name": "grid",
    "key": "chart.grid",
    "css": "--cui-chart-grid",
    "value": "{border.subtle}",
    "description": "Supporting chart grid lines",
    "resolved": "#dce2db",
    "darkResolved": "#47574b"
  },
  {
    "group": "chart",
    "name": "label",
    "key": "chart.label",
    "css": "--cui-chart-label",
    "value": "{text.secondary}",
    "description": "Chart axis and legend text",
    "resolved": "#5e665f",
    "darkResolved": "#bdc7bf"
  },
  {
    "group": "chart",
    "name": "radius",
    "key": "chart.radius",
    "css": "--cui-chart-radius",
    "value": "4px",
    "description": "Subtle bar-end radius",
    "resolved": "4px",
    "darkResolved": "4px"
  },
  {
    "group": "chart",
    "name": "stroke",
    "key": "chart.stroke",
    "css": "--cui-chart-stroke",
    "value": "2px",
    "description": "Chart series stroke width",
    "resolved": "2px",
    "darkResolved": "2px"
  }
] as const
export const tokens = {
  "colour.ink": "#171717",
  "colour.muted": "#5e665f",
  "colour.paper": "#faf9f7",
  "colour.band": "#eef0ec",
  "colour.white": "#ffffff",
  "colour.line": "#dce2db",
  "colour.control": "#829080",
  "colour.forest": "#27382f",
  "colour.sage": "#c9deb6",
  "colour.chart": "#499e6b",
  "colour.positive": "#2f6b45",
  "colour.warning": "#8a5a1a",
  "colour.negative": "#a13d32",
  "surface.page": "#faf9f7",
  "surface.band": "#eef0ec",
  "surface.card": "#ffffff",
  "surface.selected": "#c9deb6",
  "surface.warning": "#f7e6c8",
  "surface.hover": "#eef0ec",
  "dropdown.hover": "#eef0ec",
  "dropdown.selected": "#dce2db",
  "text.primary": "#171717",
  "text.secondary": "#5e665f",
  "text.inverse": "#ffffff",
  "text.accent": "#27382f",
  "text.positive": "#2f6b45",
  "text.warning": "#8a5a1a",
  "text.negative": "#a13d32",
  "border.subtle": "#dce2db",
  "border.control": "#829080",
  "border.error": "#a13d32",
  "border.width": "1px",
  "accent.primary": "#27382f",
  "accent.soft": "#c9deb6",
  "accent.chart": "#499e6b",
  "space.0": "0px",
  "space.4": "4px",
  "space.8": "8px",
  "space.12": "12px",
  "space.16": "16px",
  "space.20": "20px",
  "space.24": "24px",
  "space.32": "32px",
  "space.40": "40px",
  "space.48": "48px",
  "space.64": "64px",
  "font.sans": "Roobert, Geist, Arial, sans-serif",
  "font.regular": "400",
  "font.medium": "500",
  "font.semibold": "600",
  "type.display": "2.5rem",
  "type.display-leading": "3rem",
  "type.display-mobile": "2rem",
  "type.display-mobile-leading": "2.5rem",
  "type.section": "1.25rem",
  "type.section-leading": "1.75rem",
  "type.body": "1rem",
  "type.body-leading": "1.5rem",
  "type.compact": ".875rem",
  "type.compact-leading": "1.25rem",
  "type.caption": ".75rem",
  "type.caption-leading": "1rem",
  "type.data": "1.5rem",
  "type.data-leading": "2rem",
  "type.tracking-display": "-.02em",
  "type.tracking-heading": "-.01em",
  "radius.band": "16px",
  "radius.card": "12px",
  "radius.control": "8px",
  "radius.round": "50%",
  "shadow.card": "0 4px 12px rgba(23, 23, 23, 0.06)",
  "shadow.none": "none",
  "focus.colour": "#27382f",
  "focus.width": "2px",
  "focus.offset": "0px",
  "size.control": "40px",
  "size.touch": "48px",
  "size.row": "44px",
  "size.icon": "20px",
  "size.icon-small": "16px",
  "size.brand": "24px",
  "size.sidebar": "208px",
  "size.rail": "64px",
  "size.content": "1280px",
  "motion.duration": "160ms",
  "motion.easing": "ease-out",
  "breakpoint.mobile": "650px",
  "breakpoint.sidebar": "900px",
  "layer.navigation": "20",
  "layer.overlay": "40",
  "layer.dialog": "50",
  "chart.series-primary": "#27382f",
  "chart.series-secondary": "#499e6b",
  "chart.series-tertiary": "#5e665f",
  "chart.grid": "#dce2db",
  "chart.label": "#5e665f",
  "chart.radius": "4px",
  "chart.stroke": "2px"
} as const
export const darkTokens = {
  "colour.ink": "#171717",
  "colour.muted": "#5e665f",
  "colour.paper": "#faf9f7",
  "colour.band": "#eef0ec",
  "colour.white": "#ffffff",
  "colour.line": "#dce2db",
  "colour.control": "#829080",
  "colour.forest": "#27382f",
  "colour.sage": "#c9deb6",
  "colour.chart": "#499e6b",
  "colour.positive": "#2f6b45",
  "colour.warning": "#8a5a1a",
  "colour.negative": "#a13d32",
  "surface.page": "#171c19",
  "surface.band": "#202823",
  "surface.card": "#28312b",
  "surface.selected": "#27382f",
  "surface.warning": "#3a2e18",
  "surface.hover": "#344139",
  "dropdown.hover": "#344139",
  "dropdown.selected": "#47574b",
  "text.primary": "#faf9f7",
  "text.secondary": "#bdc7bf",
  "text.inverse": "#171717",
  "text.accent": "#c9deb6",
  "text.positive": "#a3d8b4",
  "text.warning": "#f0c98a",
  "text.negative": "#ffb4a8",
  "border.subtle": "#47574b",
  "border.control": "#95a78f",
  "border.error": "#ffb4a8",
  "border.width": "1px",
  "accent.primary": "#c9deb6",
  "accent.soft": "#27382f",
  "accent.chart": "#499e6b",
  "space.0": "0px",
  "space.4": "4px",
  "space.8": "8px",
  "space.12": "12px",
  "space.16": "16px",
  "space.20": "20px",
  "space.24": "24px",
  "space.32": "32px",
  "space.40": "40px",
  "space.48": "48px",
  "space.64": "64px",
  "font.sans": "Roobert, Geist, Arial, sans-serif",
  "font.regular": "400",
  "font.medium": "500",
  "font.semibold": "600",
  "type.display": "2.5rem",
  "type.display-leading": "3rem",
  "type.display-mobile": "2rem",
  "type.display-mobile-leading": "2.5rem",
  "type.section": "1.25rem",
  "type.section-leading": "1.75rem",
  "type.body": "1rem",
  "type.body-leading": "1.5rem",
  "type.compact": ".875rem",
  "type.compact-leading": "1.25rem",
  "type.caption": ".75rem",
  "type.caption-leading": "1rem",
  "type.data": "1.5rem",
  "type.data-leading": "2rem",
  "type.tracking-display": "-.02em",
  "type.tracking-heading": "-.01em",
  "radius.band": "16px",
  "radius.card": "12px",
  "radius.control": "8px",
  "radius.round": "50%",
  "shadow.card": "0 4px 12px rgba(0, 0, 0, 0.2)",
  "shadow.none": "none",
  "focus.colour": "#c9deb6",
  "focus.width": "2px",
  "focus.offset": "0px",
  "size.control": "40px",
  "size.touch": "48px",
  "size.row": "44px",
  "size.icon": "20px",
  "size.icon-small": "16px",
  "size.brand": "24px",
  "size.sidebar": "208px",
  "size.rail": "64px",
  "size.content": "1280px",
  "motion.duration": "160ms",
  "motion.easing": "ease-out",
  "breakpoint.mobile": "650px",
  "breakpoint.sidebar": "900px",
  "layer.navigation": "20",
  "layer.overlay": "40",
  "layer.dialog": "50",
  "chart.series-primary": "#c9deb6",
  "chart.series-secondary": "#72be90",
  "chart.series-tertiary": "#bdc7bf",
  "chart.grid": "#47574b",
  "chart.label": "#bdc7bf",
  "chart.radius": "4px",
  "chart.stroke": "2px"
} as const
export type TokenName = keyof typeof tokens
